USE ADMINISTRADORA;

-- SELECT * FROM PROPRIETARIO;
-- SELECT * FROM unidade_habitacional;
-- SELECT * FROM taxa;
-- SELECT * FROM ALUGUEL;
-- SELECT * FROM venda;

/*RELAÇÃO DE UNIDADES HABITACIONAIS E OS RESPECTIVOS NOMES DOS CONDÔMINOS*/
SELECT U.IDUNIDADE, P.NOME, P.IDPROPRIETARIO 
FROM UNIDADE_HABITACIONAL U
INNER JOIN PROPRIETARIO P
ON P.IDPROPRIETARIO = U.ID_PROPRIETARIO
ORDER BY U.IDUNIDADE;

/* RELAÇÕES DE SÍNDICOS(NOME) E PERÍODO DE VIGÊNCIA AO LONGO DA HISTÓRIA
   DO CONDOMÍNIO */
SELECT 
S.ID_PROPRIETARIO, 
P.NOME, 
S.ID_CONDOMINIO, 
S.TEMPO_EM_MESES AS "TEMPO EM MESES",
DATEDIFF(S.VIGENCIA_TERMINO,S.VIGENCIA_INICIO) AS "DIAS DE ATUAÇÃO",
S.VIGENCIA_INICIO, S.VIGENCIA_TERMINO
FROM SINDICO S
INNER JOIN PROPRIETARIO P
ON P.IDPROPRIETARIO = S.ID_PROPRIETARIO;

/* RELAÇÃO DE UNIDADES HABITACIONAIS ALUGADAS COM O NOME DO PROPRIETÁRIO
	E O NOME DO INQUILINO */
SELECT A.ID_UNIDADE_HABITACIONAL, 
		 L.NOME AS 'INQUILINO', 
		 P.NOME AS 'PROPRIETARIO'
FROM ALUGUEL A
INNER JOIN locatario L
ON L.IDLOCATARIO = A.ID_LOCATARIO
INNER JOIN proprietario P
ON P.IDPROPRIETARIO = A.ID_PROPRIETARIO;

/* RELAÇÃO DE UNIDADES HABITACIONAIS QUE ESTÃO EM DÉBITO DA TAXA 
	DE CONDOMÍNIO.
	DEFINIMOS QUE A MULTA DE ATRASO NÃO É PAGA NO MESMO MÊS, POR ISSO O
	ATRASO CONSTA COMO DÉBITO */
SELECT T.ID_UNIDADE_HABITACIONAL AS "UNIDADE EM DÉBITO", T.ID_CONDOMINIO, 
P.NOME
FROM taxa T
INNER JOIN unidade_habitacional U
ON U.IDUNIDADE = T.ID_UNIDADE_HABITACIONAL
INNER JOIN proprietario P
ON P.IDPROPRIETARIO = U.ID_PROPRIETARIO
INNER JOIN recebimento R
ON R.ID_TAXA = T.IDTAXA
WHERE R.DATA_PAGAMENTO IS NULL
		OR	DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) < 0; 

/* EXIBIR O TOTAL DE DÉBITO DE CADA UMA DESTAS UNIDADE HABITACIONAIS*/
SELECT P.NOME AS "PROPRIETARIO", U.IDUNIDADE AS "UNIDADE", 
IF(DATEDIFF (R.DATA_PAGAMENTO,R.VIGENCIA) > 0, 
"PAGAMENTO ATRASADO","SEM ATRASO") 
AS "SITUAÇÃO",

CASE
	WHEN DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) IS NULL
		THEN "-"
	WHEN DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) > 1
		THEN "-"
	WHEN DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) < 1
		THEN DATEDIFF(R.DATA_PAGAMENTO, R.VIGENCIA)
END AS "DIAS DE ATRASO", 

CASE
	WHEN DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) IS NULL
		THEN "-"
	WHEN DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) < 0
		THEN (-DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO)/30) * VALOR
	WHEN DATEDIFF(R.VIGENCIA, R.DATA_PAGAMENTO) > 1
		THEN "-"
END AS "DÉBITO TOTAL"

FROM UNIDADE_HABITACIONAL U
INNER JOIN TAXA T
ON U.IDUNIDADE = T.ID_UNIDADE_HABITACIONAL
INNER JOIN proprietario P
ON U.ID_PROPRIETARIO = P.IDPROPRIETARIO
INNER JOIN recebimento R
ON R.ID_TAXA = T.IDTAXA;

/* DADO UMA UNIDADE HABITACIONAL E UM PERÍODO ESPECÍFICO
	EXIBIR TODOS OS PAGAMENTOS, VALORES, DATA DE VENCIMENTO E 
	DATA DE PAGAMENTO */
	
	SELECT 
	P.NOME AS "PROPRIETÁRIO", 
	U.IDUNIDADE, 
	R.VALOR, 
	R.VIGENCIA AS "DATA DE VENCIMENTO", 
	R.DATA_PAGAMENTO AS "DATA DE PAGAMENTO"
	FROM recebimento R
	INNER JOIN taxa T
	ON T.IDTAXA = R.ID_TAXA
	INNER JOIN unidade_habitacional U
	ON U.IDUNIDADE = T.ID_UNIDADE_HABITACIONAL
	INNER JOIN proprietario P
	ON P.IDPROPRIETARIO = U.ID_PROPRIETARIO
	WHERE U.IDUNIDADE IN (1,2,3)
	ORDER BY U.IDUNIDADE;